-- schema.sql
-- Purpose: Define database schema
-- Functionality:
--   - Create tables for voters, codes, fingerprints, ballots, signatures
-- What it does:
--   - Executes SQL statements to create tables
-- Returns:
--   - None
-- Notes:
--   - Contributors should update schema before altering database structure